apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapi
  namespace: weather
  labels:
    app: weatherapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherapi
  template:
    metadata:
      labels:
        app: weatherapi
    spec:
      containers:
      - name: weatherapi
        image: 01521433811/weatherapi:TAG_NUMBER
        env:
          - name: OPENWEATHERMAP_API_KEY
            valueFrom:
              secretKeyRef:
                name: openweathermap-api-key
                key: api-key

        ports:
        - name: http
          protocol: TCP
          containerPort: 80
        resources:
          requests:
            cpu: "10m"
            memory: 100Mi
          limits:
            cpu: "100m"
            memory: 1000Mi

---
apiVersion: v1
kind: Service
metadata:
  name: weatherapi
  namespace: weather
spec:
  selector:
    app: weatherapi
  type: LoadBalancer
  ports:
  - name: http
    nodePort: 30048
    port: 80
    targetPort: 80
    protocol: TCP
