- hosts: masters
  become: yes
  tasks:
    - name: Run command to get eth1 IP address
      shell: ip addr show eth1 | grep 'inet ' | awk '{print $2}'
      register: eth1_ip_result
      ignore_errors: yes

    - name: Set master_ip variable
      set_fact:
        master_ip: "{{ eth1_ip_result.stdout }}"
      when: eth1_ip_result.rc == 0

    - name: Initialize the cluster
      shell: kubeadm init --pod-network-cidr={{ master_ip }}
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      file:
        path: $HOME/.kube
        state: directory
        mode: 0754

    - name: copies admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes

    - name: install Pod network
      become: yes
      shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
      args:
        chdir: $HOME

    - name: Get the token for joining the worker nodes
      become: yes
      become_user: root
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command

    #- debug:
    #  msg: "{{ kubernetes_join_command.stdout }}"

    - name: Copy join command to local file.
      become: yes
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/home/kubernetes_join_command" mode=0777

